import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryService implements InMemoryDbService {
  createDb() {
    let works = [
      {id: 1,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 2,name:'AOI機械月保養', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 3,name:'as required', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 4,name:'A月保養', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 5,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 6,name:'CE周保養', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 7,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 8,name:'COCFE年保養', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 9,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 10,name:'EOC周保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 11,name:'FMD2年保養', content:'每隔兩年保養一次', period: 2, unit:'Year(年)', monthPlan:'Y', weekPlan:'N'},
      {id: 12,name:'FMD2月保養', content:'每隔兩月保養一次', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 13,name:'FMD季保養', content:'4DZB季保養', period: 3, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 14,name:'FMD月保養', content:'4DZB月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 15,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 16,name:'AOI機械月保養', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 17,name:'as required', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 18,name:'A月保養', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 19,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 20,name:'CE周保養', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 21,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 22,name:'COCFE年保養', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 23,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 24,name:'EOC周保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 25,name:'FMD2年保養', content:'每隔兩年保養一次', period: 2, unit:'Year(年)', monthPlan:'Y', weekPlan:'N'},
      {id: 26,name:'FMD2月保養', content:'每隔兩月保養一次', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 27,name:'FMD季保養', content:'4DZB季保養', period: 3, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 28,name:'FMD月保養', content:'4DZB月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 29,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 30,name:'AOI機械月保養', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 31,name:'as required', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 32,name:'A月保養', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 33,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 34,name:'CE周保養', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 35,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 36,name:'COCFE年保養', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 37,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 38,name:'EOC周保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 39,name:'FMD2年保養', content:'每隔兩年保養一次', period: 2, unit:'Year(年)', monthPlan:'Y', weekPlan:'N'},
      {id: 40,name:'FMD2月保養4', content:'每隔兩月保養一次', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 41,name:'2月保養4', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 42,name:'AOI機械月保養4', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 43,name:'as required4', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 44,name:'A月保養4', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 45,name:'BOSE功能測試機械月保養4', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 46,name:'CE周保養4', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 47,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 48,name:'COCFE年保養', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 49,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 50,name:'EOC周保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 51,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 52,name:'AOI機械月保養5', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 53,name:'as required5', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 54,name:'A月保養5', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 55,name:'BOSE功能測試機械月保養5', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 56,name:'CE周保養5', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 57,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 58,name:'COCFE年保養5', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 59,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 60,name:'EOC周保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 61,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 62,name:'AOI機械月保養', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 63,name:'as required', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 64,name:'A月保養6', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 65,name:'BOSE功能測試機械月保養6', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 66,name:'CE周保養', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 67,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 68,name:'COCFE年保養', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 69,name:'EMDD周保養4', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 70,name:'EOC周保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 71,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 72,name:'AOI機械月保養', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 73,name:'as required5', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 74,name:'A月保養87', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 75,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 76,name:'CE周保養234', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 77,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 78,name:'COCFE年保養42', content:'每隔一年保養457', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 79,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 80,name:'EOC周保養785', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 81,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 82,name:'AOI機械月保養542', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 83,name:'as required452', content:'根據狀況需要進行保養47', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 84,name:'A月保養', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 85,name:'BOSE功能測試機械月保養587', content:'BOSE功能測試機械月保養785', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 86,name:'CE周保養785', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 87,name:'CE月保養', content:'每月固定保養一次5785', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 88,name:'COCFE年保養578', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 89,name:'EMDD周保養', content:'每周一次578', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 90,name:'EOC周保養5785', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 91,name:'2月保養', content:'每隔兩個月保養5785', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 92,name:'AOI機械月保養', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 93,name:'as required578', content:'根據狀況需要進行保養5785', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 94,name:'A月保養', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 95,name:'BOSE功能測試機械月保養587', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 96,name:'CE周保養', content:'每週固定保養5785', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 97,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 98,name:'COCFE年保養5785', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 99,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 100,name:'EOC周保養', content:'每隔兩個月保養5875', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 101,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 102,name:'AOI機械月保養5785', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 103,name:'as required', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 104,name:'A月保養', content:'設備維護578', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 105,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 106,name:'CE周保養ff', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 107,name:'CE月保養', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 108,name:'COCFE年保養fwe', content:'每隔一年保養nbfg', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 109,name:'EMDD周保養', content:'每周一次', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 110,name:'EOC周保養sf', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 111,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 112,name:'AOI機械月保養', content:'每隔一個月保養eq', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 113,name:'as requiredsfs', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 114,name:'A月保養', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 115,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養fswf', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 116,name:'CE周保養erwer', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 117,name:'CE月保養', content:'每月固定保養一次uyiy', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 118,name:'COCFE年保養vbd', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 119,name:'EMDD周保養', content:'每周一次ret', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 120,name:'EOC周保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 121,name:'2月保養w', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 122,name:'AOI機械月保養sdg', content:'每隔一個月保養dbf', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 123,name:'as required', content:'根據狀況需要進行保養', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 124,name:'A月保養', content:'設備維護gsdfg', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 125,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 126,name:'CE周保養wer', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 127,name:'CE月保養', content:'每月固定保養一次mh', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 128,name:'COCFE年保養erw', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 129,name:'EMDD周保養', content:'每周一次retr', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 130,name:'EOC周保養wrt', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 131,name:'2月保養', content:'每隔兩個月保養jj', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 132,name:'AOI機械月保養wer', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 133,name:'as required', content:'根據狀況需要進行保養bvc', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 134,name:'A月保養awfs', content:'設備維護', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 135,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養sfs', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 136,name:'CE周保養', content:'每週固定保養', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 137,name:'CE月保養werwe', content:'每月固定保養一次', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'Y'},
      {id: 138,name:'COCFE年保養', content:'每隔一年保養', period: 12, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 139,name:'EMDD周保養', content:'每周一次sfd', period: 1, unit:'Week(周)', monthPlan:'N', weekPlan:'Y'},
      {id: 140,name:'EOC周保養fsdf', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 141,name:'2月保養', content:'每隔兩個月保養', period: 2, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 142,name:'AOI機械月保養wer', content:'每隔一個月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 143,name:'as required', content:'根據狀況需要進行保養uiuy', period: 2, unit:'Week(周)', monthPlan:'N', weekPlan:'N'},
      {id: 144,name:'A月保養', content:'設備維護vbn', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'},
      {id: 145,name:'BOSE功能測試機械月保養', content:'BOSE功能測試機械月保養', period: 1, unit:'Month(月)', monthPlan:'Y', weekPlan:'N'}
    ]
    let page ={pageSize:10,pageTotal:15}

    return {works,page};
  }
}
